### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by sophie22**
DNAnexus applet using the Illumina bcl2fastq software version 2.20 from an asset stored in 001.
Can be run with input of a single sentinel record file (that gets generated by dx-streaming-upload) or an array of tar.gz packets as a result of uploading data from a (NovaSeq) sequencer using https://github.com/eastgenomics/dx-streaming-upload.
Optionally a SampleSheet.csv can be provided, which will overwrite the one from the sequencer (which may have incorrect sample naming or not exist, as it is no longer essential for sequencing).
The data from the sequencer is unpacked and the bcl files are demultiplexed by bcl2fastq with information from the SampleSheet.csv (correct naming and use of the correct barcode sequences in the SampleSheet is essential!!)
The applet then outputs the fastq files and stats from demultiplexing (Stats.json) as well as sequencing log files, mirroring the directory structure on the sequencer.
Example of the job output from the current applet version can be found [here](https://platform.dnanexus.com/projects/G1gbJ3048k0yzP545gppfVgV/monitor/job/G28Y6Y848k0QbF8FBPjq261Z)

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: all files reviewed, 10 unresolved discussions (waiting on @sophie22)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-MZrNj8u9-VD_QvuXo2s:-MZrNj8u9-VD_QvuXo2t:bufsrqs) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/dxapp.json#L2)):*
> ```
> _dev
> ```
Dev tag should be removed before release
___
*[dxapp.json, line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-MZrNzdYEVVChDAuy3N4:-MZrNzdYEVVChDAuy3N5:b-u0w2me) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/dxapp.json#L4)):*
> ```
> or higher
> ```
I guess it must use v2.20, not `or higher` ?
___
*[src/code.sh, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_-zc8vDar2zjoMTJA0:-M_-zc8w85CLHh5KiWRu:b4osj0j) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L91)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>   # if not, check if its present along with the sentinel record
>     # get the samplesheet id from the sentinel record and download it
>   # elif [ -n "${upload_sentinel_record}" ]; then
>   #   sample_sheet_id=$(dx get_details "${upload_sentinel_record}" | jq -r .samplesheet_file_id)
>   #   if [ "${sample_sheet_id}" ==  "null"  ]; then
>   #     dx-jobutil-report-error "Samplesheet was not found." AppInternalError
>   #   else
>   #     dx download -f "${sample_sheet_id}" -o SampleSheet.csv
>   #   fi
> ```
</details>

Why is this section commented? Does it need to be restored now that you have restored the sentinel input?
___
*[src/code.sh, line 97 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0530UERmMZK8UBqbN:-M_0530UERmMZK8UBqbO:b-j4io80) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L97)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   #   if [ "${sample_sheet_id}" ==  "null"  ]; then
>   #     dx-jobutil-report-error "Samplesheet was not found." AppInternalError
>   #   else
>   #     dx download -f "${sample_sheet_id}" -o SampleSheet.csv
>   #   fi
> ```
</details>

Why commented out?
___
*[src/code.sh, line 122 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0-FK24vYvh5qsqGTu:-M_0-FK24vYvh5qsqGTv:b-c0w6bo) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L122)):*
> ```
> # /usr/bin/bcl2fastq $advanced_opts
> ```
Remove if not required
___
*[src/code.sh, line 124 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_05ozWBbEpa5-dPBGZ:-M_05ozWBbEpa5-dPBG_:b-oow4eg) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L124)):*
> ```
> # # Annotating R1 reads
> ```
These annotation sections seem to be flagging fastqs as fails if they are below size_limit.
size_limit is never set so this does nothing.
Remove both blocks (R1/R2)
___
*[src/code.sh, line 132 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_00VuH5tb5JUzLIvCL:-M_00VuH5tb5JUzLIvCM:bbkqbsj) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L132)):*
> ```
> #prefix=`echo $file | cut -d '/' -f7 |  cut -d  '_' -f1`
> ```
Remove if not required
___
*[src/code.sh, line 151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_00gJr8z5MQvdKo4-x:-M_00gJsCvsmTJ7zGPVu:bbkqbsj) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L151)):*
> ```
> #prefix=`echo $file | cut -d '/' -f7 |  cut -d  '_' -f1`
> ```
Remove if not required
___
*[src/code.sh, line 170 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_02uqLEC6C50AJkhuU:-M_02uqLEC6C50AJkhuV:bhjdx1j) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L170)):*
> ```
> look for R1 fastq files and upload them
> ```
This seems to do every fastq, not just R1
___
*[src/code.sh, line 181 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_03VhED_VmsCBtRJEq:-M_03VhED_VmsCBtRJEr:boskfqy) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L181)):*
> ```Shell
>   # mkdir ${out_reads2}/fastqs
>   # mv ./Data/Intensities/BaseCalls/*_R2_*.fastq.gz ${out_reads2}/fastqs
> ```

Can we upload everything except bcls, and retain the folder structure please?
 - don't flatten Data/Intensities/BaseCalls
 - keep fastqs where they are

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[src/code.sh, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_-zc8vDar2zjoMTJA0:-M_0E1vvB4NLcCMi9Dpb:bh9dip5) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L91)):*
> s this section commented? Does it need to be restored now that you have restored the sentine
last time we checked the sentinel record and it does not have a special field for the sample_sheet_id. Leaving it in and running with a single sentinel record as input breaks the code, because this section fails. 
Another option would be to swap this section with the one below that looks for the SampleSheet in the unpacked data (where it will likely find the SampleSheet)
___
*[src/code.sh, line 97 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0530UERmMZK8UBqbN:-M_0Eo500fBySazmABWQ:bmjjyif) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L97)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>   #   if [ "${sample_sheet_id}" ==  "null"  ]; then
>   #     dx-jobutil-report-error "Samplesheet was not found." AppInternalError
>   #   else
>   #     dx download -f "${sample_sheet_id}" -o SampleSheet.csv
>   #   fi
> ```
Why commented out?
</blockquote></details>

same as above, these belong together as one section

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-MZrNj8u9-VD_QvuXo2s:-M_0Gt0fDw-m-xgVGWOa:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/dxapp.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> _dev
> ```
Dev tag should be removed before release
</blockquote></details>

Done.
___
*[dxapp.json, line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-MZrNzdYEVVChDAuy3N4:-M_0Gs6m64z-lHBR8n03:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> or higher
> ```
I guess it must use v2.20, not `or higher` ?
</blockquote></details>

Done.
___
*[src/code.sh, line 97 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0530UERmMZK8UBqbN:-M_0LLKdCY9Gte3TsaUK:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L97)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

same as above, these belong together as one section
</blockquote></details>

Done.
___
*[src/code.sh, line 122 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0-FK24vYvh5qsqGTu:-M_0LSEWDtn-frdBIxzC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L122)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> # /usr/bin/bcl2fastq $advanced_opts
> ```
Remove if not required
</blockquote></details>

Done.
___
*[src/code.sh, line 124 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_05ozWBbEpa5-dPBGZ:-M_0LTiX8b335iWYTams:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L124)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> # # Annotating R1 reads
> ```
These annotation sections seem to be flagging fastqs as fails if they are below size_limit.
size_limit is never set so this does nothing.
Remove both blocks (R1/R2)
</blockquote></details>

Done.
___
*[src/code.sh, line 132 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_00VuH5tb5JUzLIvCL:-M_0Lqa8-NjAe9TLZH_U:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L132)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> #prefix=`echo $file | cut -d '/' -f7 |  cut -d  '_' -f1`
> ```
Remove if not required
</blockquote></details>

Done.
___
*[src/code.sh, line 151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_00gJr8z5MQvdKo4-x:-M_0LrvCAE4CrdwEvETC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L151)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> #prefix=`echo $file | cut -d '/' -f7 |  cut -d  '_' -f1`
> ```
Remove if not required
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[src/code.sh, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_-zc8vDar2zjoMTJA0:-M_0a5olAK8FAHjRiFBt:b-kphhn0) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L91)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

> s this section commented? Does it need to be restored now that you have restored the sentine
last time we checked the sentinel record and it does not have a special field for the sample_sheet_id. Leaving it in and running with a single sentinel record as input breaks the code, because this section fails. 
Another option would be to swap this section with the one below that looks for the SampleSheet in the unpacked data (where it will likely find the SampleSheet)
</blockquote></details>

Discussed, OK. Will uncomment
___
*[src/code.sh, line 170 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_02uqLEC6C50AJkhuU:-M_0aTx_8VTb-CU5Iv6k:b32w0x) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L170)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> look for R1 fastq files and upload them
> ```
This seems to do every fastq, not just R1
</blockquote></details>

OK
___
*[src/code.sh, line 130 at r2](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0aW_V932j1FEsja3J:-M_0aW_V932j1FEsja3K:b-jgtaxu) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/bb151cad71b64e8d070d83a51577fc0923a29848/src/code.sh#L130)):*
> ```
> echo $meow
> ```
Remove

**Comment by sophie22** [comment]
Job of current version: https://platform.dnanexus.com/projects/G1gbJ3048k0yzP545gppfVgV/monitor/job/G29z6Kj48k0yZ57Z284227Bb

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[src/code.sh, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_-zc8vDar2zjoMTJA0:-M_0vot762r81v87eTbn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L91)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Discussed, OK. Will uncomment
</blockquote></details>

Done.
___
*[src/code.sh, line 181 at r1](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_03VhED_VmsCBtRJEq:-M_0vssh9QhQ3ivbF_nQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/744f027262750f42c7b2c7477819f9ce4fc97ff5/src/code.sh#L181)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can we upload everything except bcls, and retain the folder structure please?
 - don't flatten Data/Intensities/BaseCalls
 - keep fastqs where they are
</blockquote></details>

Done.
___
*[src/code.sh, line 130 at r2](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1#-M_0aW_V932j1FEsja3J:-M_0vq7Y4vSrrj5BrMkq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_bcl2fastq/blob/bb151cad71b64e8d070d83a51577fc0923a29848/src/code.sh#L130)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> echo $meow
> ```
Remove
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_bcl2fastq/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sophie22)

**Pull request merged**
